### ISSUE TITLE
Document which RPC features are implemented

### ISSUE THREAD

**Issue by swsnider** [zombiezen/go-capnproto2#16]
Can you please document which level of the cap'n proto API this library implements? Thanks!

**Comment by zombiezen** [comment]
The news in the [wiki](https://github.com/zombiezen/go-capnproto2/wiki) notes it, but it is (mostly) Level 1.  The only exception is wire promises -- tracking in #2.  I can call this out more in the README.

**Comment by swsnider** [comment]
Ah, I missed that -- README would be even better though -- Thanks!
