### ISSUE TITLE
Add benchmarks for string field as bytes access

### ISSUE THREAD

**Issue by zombiezen** [zombiezen/go-capnproto2#19]
Follow-on to #18: port over benchmarks from https://github.com/glycerine/go-capnproto/blob/master/stringbytes_test.go.

**Comment by glycerine** [comment]
There are some benchmarks here where I demonstrate getting zero-allocation unmarshalling (a major design point of Capnproto) out of v1. v2 does 16 allocs for the same benchmark (15 of which can likely be eliminated, 1 is just an interface conversion endemic to the test).

https://github.com/glycerine/go_serialization_benchmarks/blob/master/serialization_benchmarks_test.go

~~~
BenchmarkCapNProtoUnmarshal-4            5000000           225 ns/op           0 B/op          0 allocs/\
op
BenchmarkCapNProto2Unmarshal-4           1000000          2379 ns/op         640 B/op         16 allocs/\
op
~~~

**Comment by zombiezen** [comment]
I got around to investigating this today. There are some easy reductions and some less easy reductions.  I'm not quite comfortable with the concept of porting `ReadFromMemoryZeroCopyNoAlloc`, since it seems like a leaky abstraction. I'd rather make it so that the allocations are reduced without a drastic change in call path.

The main source of trouble at the moment is the conversion back and forth from `Pointer`. I think I can introduce a union-esque type that avoids these allocations in a non-breaking way.
