### ISSUE TITLE
Vanity url HTML is mildly malformed

### ISSUE THREAD

**Issue by colinmarc** [zombiezen/go-capnproto2#26]
```
$ curl https://zombiezen.com/go/capnproto2
<meta name="go-import" content="zombiezen.com/go/capnproto2 git https://github.com/zombiezen/go-capnproto2">
<h1>zombiezen.com/go/capnproto2</h1>
<a href="https://github.com/zombiezen/go-capnproto2">Git Repository on GitHub</a>
```

The `meta` tag should self-close. Also, it'd be nice to have `<!DOCTYPE html>` and put the meta tags in a `<head>`, like the canonical example:

```
$ curl rsc.io/pdf
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="go-import" content="rsc.io/pdf git https://github.com/rsc/pdf">
<meta http-equiv="refresh" content="0; url=https://godoc.org/rsc.io/pdf">
</head>
<body>
Nothing to see here; <a href="https://godoc.org/rsc.io/pdf">move along</a>.
</body>
</html>
```

Obviously this is pretty minor, but for some reason it's breaking [gvt](https://github.com/FiloSottile/gvt/issues/31).

**Comment by zombiezen** [comment]
I did forget to add the DOCTYPE (fixed now), but if there are tools out there that are parsing the page for a `go get` as XML, that's incorrect.  Web pages are HTML, and the page is valid HTML5 ([validator result](https://validator.w3.org/nu/?doc=https%3A%2F%2Fzombiezen.com%2Fgo%2Fcapnproto2)).

**Comment by colinmarc** [comment]
The go tool itself [does that](https://golang.org/src/cmd/go/discovery.go) (parses it as XML), although I can't figure out why it's not breaking and gvt is. 

I get what you're saying, but would it be reasonable to close the meta tag as an expedient fix for users of capnproto who are also using gvt? Or to wrap it with the h1 in a `<head>`? That wouldn't make the html5 invalid.

**Comment by zombiezen** [comment]
Done. But this really is a gvt bug; `go get` works fine.

**Comment by colinmarc** [comment]
Agreed. Thank you!
