### ISSUE TITLE
Include base capnproto schemas

### ISSUE THREAD

**Issue by zenhack** [zombiezen/go-capnproto2#30]
I'm working on wrappers for sandstorm's APIs, at:

https://github.com/zenhack/go.sandstorm

Currently it just includes some scripts (with their output) that call capnpc-go on the sandstorm APIs, as well as the base capnproto schemas (as those are dependencies). It might make sense to include the latter in this repository, since those aren't sandstorm specific. Thoughts?

**Comment by zombiezen** [comment]
Sounds like a good idea, although I'm not sure what to recommend for include path.  I'd be happy to look at a PR for this. :+1:

What do the other language bindings do?

**Comment by zombiezen** [comment]
Also, I'm happy that you're writing a package to glue together `net/http` and `WebSession`. I've been wanting that to exist for a while.  Let me know if #2 comes to bite you.. I vaguely recall that `WebSession` uses it.

**Comment by zenhack** [comment]
I'll try cooking something up. Question: in the file:

https://github.com/zombiezen/go-capnproto2/blob/master/internal/schema/gen.go

Why are we passing `-promises=false`?

**Comment by zombiezen** [comment]
Because we don't need it to run capnpc-go. While I was making breaking API changes, it reduced the surface area that I had to manually clean up if I broke something.  Not too much of a pragmatic reason for it now, other than keeping codegen size low.

**Comment by zombiezen** [comment]
Closed by 41a9c8d
