### ISSUE TITLE
Import failed: zombiezen.com/go/capnproto2/go.capnp

### ISSUE THREAD

**Issue by zhaoguojie2010** [zombiezen/go-capnproto2#36]
Greetings,
I was trying to generate go files by running:
$ ` capnp compile -ogo message/books.capnp
`
message/books.capnp is as follow:
```
using Go = import "zombiezen.com/go/capnproto2/go.capnp";
@0x85d3acc39d94e0f8;
$Go.package("message");
$Go.import("myProject/message");

struct Book {
    title @0 :Text;
    # Title of the book.

    pageCount @1 :Int32;
    # Number of pages in the book.
}
```

Then i get 

> message/books.capnp:1:19-57: error: Import failed: zombiezen.com/go/capnproto2/go.capnp
> message/books.capnp:3:2-4: error: Not defined: Go
> message/books.capnp:4:2-4: error: Not defined: Go

How do i fix this? Thanks.

**Comment by zhaoguojie2010** [comment]
BTW, when i run : go get -u zombiezen.com/go/capnproto2/...
I get: package golang.org/x/net/context: directory "/go/src/golang.org/x/net/context" is not using a known version control system

under dir: /go/src/golang.org/x/net/context,
i have three files, context.go	    go17.go		pre_go17.go

Is it possible that it has something to do with this??

**Comment by oeegor** [comment]
@zhaoguojie2010 try to change your import to this: `zombiezen.com/go/capnproto2/std/go.capnp` because it seems the file has been moved without updating docs.

**Comment by zombiezen** [comment]
@oeegor has the right idea. The `internal/demo/` directory already had the fixed version, but I forgot to update the wiki (done).  I really wish GitHub wiki had a way of including code snippets from the repo so the two would not fall out of sync.

**Comment by zhaoguojie2010** [comment]
@oeegor @zombiezen  hello guys, it does not solve the problem.
`capnp compile -ogo message.capnp`

> message.capnp:1:19-61: error: Import failed: zombiezen.com/go/capnproto2/std/go.capnp
> message.capnp:3:2-4: error: Not defined: Go
> message.capnp:4:2-4: error: Not defined: Go

and when i goes to this dir: 

> zombiezen.com/go/capnproto2/internal/demo/books
and run: `capnp compile -ogo books.capnp`
I get this: 

> books.capnp:1:19-30: error: Import failed: /go.capnp
> books.capnp:3:2-4: error: Not defined: Go
> books.capnp:4:2-4: error: Not defined: Go

BTW: I'm using capnp v0.5.3
