### ISSUE TITLE
Setting field type as another struct results in import error

### ISSUE THREAD

**Issue by oeegor** [zombiezen/go-capnproto2#37]
When I have this simple schema
```
# schema/example.capnp
@0xb42bbb69f69a82f8;

using Go = import "../vendor/zombiezen.com/go/capnproto2/std/go.capnp";
$Go.package("main");


struct A {
    b @0 :B;
}
struct B {}
```

And then run `capnp compile -ogo example.capnp` I get error: 
```
capnpc-go: generating example.capnp: field A.b: internal error (bad schema?): missing import declaration for example.capnp:B
go: plugin failed: exit code 1
```

Is something wrong with my schema or is it a bug?

**Comment by zombiezen** [comment]
The error message could probably be better here, but it's that you are missing a `$Go.import` annotation in your schema.  This is currently lazily evaluated, but perhaps it should be checked earlier.

**Comment by oeegor** [comment]
oh, with `$Go.import` annotation it works, I doesn't know that including that annotation is required.
