### ISSUE TITLE
Import failed: zombiezen.com/go/capnproto2/std/go.capnp

### ISSUE THREAD

**Issue by zhaoguojie2010** [zombiezen/go-capnproto2#39]
As mentioned in issue #36 . I changed import path to: `zombiezen.com/go/capnproto2/std/go.capnp`

`capnp compile -ogo message.capnp`

> message.capnp:1:19-61: error: Import failed: zombiezen.com/go/capnproto2/std/go.capnp
> message.capnp:3:2-4: error: Not defined: Go
> message.capnp:4:2-4: error: Not defined: Go

and when i go to this dir:

> zombiezen.com/go/capnproto2/internal/demo/books

and run: `capnp compile -ogo books.capnp`
I get this:

> books.capnp:1:19-30: error: Import failed: /go.capnp
> books.capnp:3:2-4: error: Not defined: Go
> books.capnp:4:2-4: error: Not defined: Go

BTW: I'm using capnp v0.5.3

**Comment by zombiezen** [comment]
You need to also pass the `-I` flag.  You can see how this is done in internal/demo/books/gen.go, but I've also now documented it in [Getting Started](https://github.com/zombiezen/go-capnproto2/wiki/Getting-Started).

**Comment by zombiezen** [comment]
Marking closed.  Feel free to open back up if this didn't work for you.
