### ISSUE TITLE
Has* methods on messages ambiguous for union types.

### ISSUE THREAD

**Issue by abraithwaite** [zombiezen/go-capnproto2#55]
Just noticed this.  If you have a union type in a struct and you check `msg.Has*` for the different union types, they'll both return true if only one is set.

From the generated code:
```golang
func (s Message) HasLog() bool {
    p, err := s.Struct.Ptr(1)
    return p.IsValid() || err != nil
}
```
```golang
func (s Message) HasRequest() bool {
    p, err := s.Struct.Ptr(1)
    return p.IsValid() || err != nil
}
```

**Comment by abraithwaite** [comment]
Not sure if anything _needs_ to be done about this.  Maybe a little documentation is all.

**Comment by zombiezen** [comment]
Hm. While in general the behavior of using the wrong union field is undefined, perhaps there should be more explicit checking.  What does the C++ implementation do?

**Comment by zombiezen** [comment]
C++ does do this check.  It also makes assertions for every union member access that `which` matches.

**Comment by zombiezen** [comment]
Forgot to mention: I opened #56 to add runtime assertions for other accessor methods.
