### ISSUE TITLE
zombiezen.com checkout path doesn't work

### ISSUE THREAD

**Issue by kormat** [zombiezen/go-capnproto2#58]
zombiezen.com has been broken for a few days, breaking checking out the go-capnproto2 project. E.g.:

```
Fetching https://zombiezen.com/go/capnproto2?go-get=1
https fetch failed: Get https://zombiezen.com/go/capnproto2?go-get=1: EOF
package zombiezen.com/go/capnproto2: unrecognized import path "zombiezen.com/go/capnproto2" (https fetch: Get https://zombiezen.com/go/capnproto2?go-get=1: EOF)
```

**Comment by zombiezen** [comment]
Interesting, this appears to be a TLS connection issue.  My monitoring didn't catch this, so I'll be adding a new monitoring rule to prevent this in the future.

**Comment by zombiezen** [comment]
Okay, I think I have fixed this.  I'm waiting for my monitoring to catch up, but the underlying TLS configuration should be properly configured again.  I'm going to close for now, reopen if you can't fetch within the next few hours.
