### ISSUE TITLE
pogs: support interface types

### ISSUE THREAD

**Issue by zenhack** [zombiezen/go-capnproto2#62]
I'm trying to write some table-driven tests for go.sandstorm, and the pogs package makes this a lot easier, but it's still a bit annoying because I can't put capnp interface types in the struct literals. I don't think this should be hard to implement; we can require that capnp interface fields to have an rpc.Client field, and it should just be an assignment.

**Comment by zombiezen** [comment]
Yup, this sounds right. I omitted it just for sake of time, not really as a "it shouldn't be done".

**Comment by zenhack** [comment]
It occurs to me that implementing this properly requires access to the capability table, which *is* transitively accessable via capnp.Struct (segment -> message), but Struct.seg isn't exported, so right now this doesn't quite work from an purely external package.

(I know you're busy this week, and don't really expect a timely response, but I figure there's no harm in frontloading).

**Comment by zombiezen** [comment]
All structs have a `Segment()` method. You can always get the segment/message, you just can't modify the `seg` field.

**Comment by zenhack** [comment]
Ah, missed that. should do the trick then.

**Comment by zenhack** [comment]
(Just a note: I've got a branch where I'm working on this).

**Comment by zenhack** [comment]
#66 is merged, now, so I'm closing this.
