### ISSUE TITLE
Use net.Buffers in Go 1.8 for encoding.

### ISSUE THREAD

**Issue by tmthrgd** [zombiezen/go-capnproto2#68]
Go 1.8 [added](https://golang.org/doc/go1.8#net) a new [`net.Buffers`](https://golang.org/pkg/net/#Buffers) designed specifically for writing multiple blocks of memory to a network connection in a single system call.

> The new Buffers type permits writing to the network more efficiently from multiple discontiguous buffers in memory. On certain machines, for certain types of connections, this is optimized into an OS-specific batch write operation (such as writev).

As `net.Buffers` is essentially a 'best effort' system, writes to regular `io.Writer`'s will function identically without any change in functionality or semantics.

`writev` also ensures that the write performed will be atomic, although this **cannot** be relied upon by `net.Buffers` as it doesn't guarantee the use of `writev`. According to the [man page](https://linux.die.net/man/2/writev):

> The data transfers performed by readv() and writev() are atomic: the data written by writev() is written as a single block that is not intermingled with output from writes in other processes (but see pipe(7) for an exception).

I think the principal benefit of using `net.Buffers` would be reducing the number of system calls required in [(*Encoder).Encode](https://github.com/zombiezen/go-capnproto2/blob/02f10324cc25fc4acd262b854872e1e5bddb14f7/mem.go#L567-L599) from `1 + number of segments` to 1 in every case – with the exception of the packed encoder as it writes the packed data to a [single temporary buffer](https://github.com/zombiezen/go-capnproto2/blob/02f10324cc25fc4acd262b854872e1e5bddb14f7/mem.go#L602-L605).

**Comment by zombiezen** [comment]
Sounds like a good idea. Happy to accept PRs.
