### ISSUE TITLE
Bug: double far pointers are not resolved properly

### ISSUE THREAD

**Issue by levrado** [zombiezen/go-capnproto2#72]
while parsing a message that contained a double far pointer, I got an error.

after some investigation, I've came to a conclusion the problem lies in the `landingPadNearPointer` function in `rawpointer.go`.

the function conversion is not correct, the created pointer from the function is after a multiplication of the offset in word size, so instead of having a pointer with the some addr x - 1 (an offset in terms of word size), the returned pointer stores the address (x * wordSize - wordSize).

I've created a PR with a fix and a test, appreciate if you can take a look.

https://github.com/zombiezen/go-capnproto2/pull/71

thanks :)

**Comment by zenhack** [comment]
This should be closed, since #71 has been merged.

//cc @zombiezen

**Comment by zombiezen** [comment]
Quite right.
