### ISSUE TITLE
Add Context parameter to server methods.

### ISSUE THREAD

**Issue by zenhack** [zombiezen/go-capnproto2#77]
I find myself using context.TODO() too often. Usually when one capnproto object is calling another. It seems like it would make sense for a context to get passed through into the server objects, which they can possibly use in their own calls.

**Comment by zenhack** [comment]
There's an obvious question re: compatibility; adding the parameter would break existing instances.

**Comment by zombiezen** [comment]
I'm confused. I explicitly do have a Context in every generated "Call" struct. That is the Ctx field. Or am I missing something?

**Comment by zenhack** [comment]
/me facepalms. How did I not see that? I guess I'm so used to the first parameter idiom that I didn't really go looking elsewhere.

Closing. Sorry for the noise.

**Comment by zombiezen** [comment]
I am debating (if and when I make the Client API changes) pulling out the context as first parameter. Not sure. I really should start an experiment branch.
